app/models/address.rb, app/models/customer.rb, app/models/genre.rb, app/models/item.rb, db/migrate/20220918161945_devise_create_customers.rb, db/migrate/20220918162008_create_items.rb, db/migrate/20220919073703_create_genres.rb, db/migrate/20220919073730_create_addresses.rb, test/fixtures/addresses.yml, test/fixtures/genres.yml, test/models/address_test.rb, test/models/genre_test.rb
以下のModel,Migrateを修正しました
* item
* customer
* admin
* address
* genre
=> [Update]Model,Migrateの修正

db/migrate/20220919085016_create_active_storage_tables.active_storage.rb, db/schema.rb
=> [Add]Active_Storageをインストールしました

app/javascript/applications.scss, app/javascript/packs/application.js, package.json, yarn.lock
=> [Add]FontAwesomeの導入

Gemfile.lock, app/views/public/homes/about.html.erb, app/views/public/homes/top.html.erb, app/views/public/registrations/new.html.erb, app/views/public/sessions/new.html.erb, config/initializers/devise.rb, config/routes.rb, db/schema.rb
ログイン画面に遷移できない問題を解決しました。
ご確認お願い致します
=> Feature routes#2

app/views/admin/sessions/new.html.erb, app/views/public/registrations/new.html.erb, app/views/public/sessions/new.html.erb, config/routes.rb
=> Feature routes#3

app/views/layouts/_header.html.erb
=> [fix]ヘッダーエラー解消

app/controllers/admin/orders_controller.rb, config/routes.rb
ルーティングの記述を一部変更しました。（resourcesを使った記述に変更）
ご確認お願い致しますm(__)m
事の経緯はIssuesを見ていただけると把握できると思います
[https://github.com/takomomo202208/git-nagano-cafeVer1.0/issues/39](url)
=> Feature routes#4

app/controllers/application_controller.rb, app/controllers/public/cart_items_controller.rb, app/controllers/public/customers_controller.rb, app/controllers/public/orders_controller.rb, app/controllers/public/registrations_controller.rb, app/controllers/public/sessions_controller.rb, app/views/admin/customers/edit.html.erb, app/views/admin/customers/index.html.erb, app/views/admin/customers/show.html.erb, app/views/admin/items/edit.html.erb, app/views/admin/items/index.html.erb, app/views/admin/items/new.html.erb, app/views/admin/items/show.html.erb, app/views/public/cart_items.html.erb/index.html.erb, app/views/public/customers/edit.html.erb, app/views/public/customers/show.html.erb, app/views/public/items/index.html.erb, app/views/public/items/show.html.erb, app/views/public/orders/index.html.erb, app/views/public/orders/new.html.erb, app/views/public/orders/show.html.erb, config/routes.rb, db/migrate/20220918161945_devise_create_customers.rb, db/schema.rb
ログイン（サインアップ）からログアウトまでの作業ができるようになりました。
**ログイン操作の都合上Routesを修正しました。**ご迷惑をお掛けしますm(__)m
=> [Fix]Feature login#4

app/controllers/public/items_controller.rb, config/routes.rb
=> [fix]routes

app/controllers/admin/homes_controller.rb, app/controllers/admin/orders_controller.rb, app/javascript/applications.scss, app/javascript/packs/application.js, app/javascript/stylesheets/application.scss, app/views/admin/homes/top.html.erb, app/views/layouts/_header.html.erb, app/views/layouts/application.html.erb, config/webpack/environment.js
=> Feature customershow

app/views/public/registrations/new.html.erb
・画面仕様書
https://drive.google.com/drive/u/0/folders/18jYAQtQwcW0Y8Id01cwQqPlQnStkOTO_
・label名変更
・text_area　→　text_field に修正
=> [Update]画面仕様書に合わせて修正

app/views/admin/customers/show.html.erb
=> [update]admincustomer

app/controllers/public/sessions_controller.rb
=> [Update]退会ステータスtrueの場合新規登録画面へ遷移するように修正

app/controllers/public/items_controller.rb, app/views/public/items/_item_genre.html.erb, app/views/public/items/index.html.erb, db/seeds.rb
=> [Update]商品一覧画面

Gemfile.lock, app/controllers/public/cart_items_controller.rb, app/controllers/public/items_controller.rb, app/views/public/items/show.html.erb
=> [Fix]public --商品詳細情報表示画面の作成

app/controllers/admin/homes_controller.rb, app/controllers/public/homes_controller.rb, app/models/item.rb, app/views/public/homes/top.html.erb
=> [add]topページ商品並び替え処理追加

app/assets/stylesheets/admin/order_details.scss, app/controllers/admin/customers_controller.rb, app/controllers/admin/items_controller.rb, app/controllers/admin/order_details_controller.rb, app/controllers/admin/orders_controller.rb, app/helpers/admin/order_details_helper.rb, app/models/customer.rb, app/models/item.rb, app/models/order.rb, app/views/admin/items/show.html.erb, app/views/admin/orders/index.html.erb, app/views/admin/orders/show.html.erb, test/controllers/admin/order_details_controller_test.rb
Admin側の注文履歴機能を追加しました。（枠の作成中のためマージはまだしないでください）
=> [Add]admin側の注文履歴機能追加

app/controllers/public/sessions_controller.rb
=> [Fix]enumの追加により退会処理が正常に動作しなくなっていたため、解消

app/controllers/public/sessions_controller.rb
=> [Fix]public-ログイン後の遷移先の修正

app/controllers/public/registrations_controller.rb
=> [Fix]public-サインイン後の遷移先を変更

app/controllers/public/orders_controller.rb, app/controllers/public/registrations_controller.rb, app/models/order.rb, app/views/layouts/_header.html.erb, app/views/public/cart_items/index.html.erb, app/views/public/orders/show.html.erb, db/schema.rb
=> [Add]public修正
